import { MedusaService } from "@medusajs/framework/utils"
import { slugify } from "transliteration"
import CategoryCustomAttribute from "./models/category-custom-attribute"
import ProductCustomAttribute from "./models/product-custom-attribute"
import AttributeTemplate from "./models/attribute-template"

const models = {
  CategoryCustomAttribute,
  ProductCustomAttribute,
  AttributeTemplate,
}

// @ts-ignore - MedusaService dynamically generates methods based on models
class CustomAttributeService extends MedusaService(models) {
  async getCategoryAttributes(categoryId: string) {
    // @ts-ignore - method generated by MedusaService
    return await this.listCategoryCustomAttributes({
      category_id: categoryId,
      deleted_at: null,
      is_global: false,
    })
  }

  async getAttributesByCategoryIds(
    categoryIds: string[],
    opts: { includeGlobals?: boolean } = { includeGlobals: true }
  ) {
    // Always include global attributes (applies to every product) unless disabled
    let globalsMapped: any[] = []
    if (opts.includeGlobals) {
      // @ts-ignore - method generated by MedusaService
      const globals = await this.listCategoryCustomAttributes({
        is_global: true,
        deleted_at: null,
      })
      globalsMapped = globals.map((attr: any) => ({
        ...attr,
        inherited: true,
        source_category_id: null,
        source: "global" as const,
      }))
    }

    if (!categoryIds || categoryIds.length === 0) {
      return globalsMapped
    }

    // @ts-ignore - method generated by MedusaService
    const attributes = await this.listCategoryCustomAttributes({
      category_id: categoryIds,
      is_global: false,
      deleted_at: null,
    })
    const leafId = categoryIds[0]
    const categoryMapped = attributes.map((attr: any) => ({
      ...attr,
      inherited: attr.category_id !== leafId,
      source_category_id: attr.category_id,
      source: "category" as const,
    }))

    return [...globalsMapped, ...categoryMapped]
  }

  async createCategoryAttribute(data: {
    label: string
    type: string
    unit?: string | null
    category_id?: string | null
    is_standard?: boolean
    is_global?: boolean
    sort_order?: number
  }) {
    const key = this.generateKey(data.label)
    // @ts-ignore - method generated by MedusaService
    return await this.createCategoryCustomAttributes({
      ...data,
      key,
      unit: data.unit ?? null,
      category_id: data.category_id ?? null,
      is_standard: data.is_standard ?? false,
      is_global: data.is_global ?? false,
      sort_order: data.sort_order ?? 0,
    })
  }

  async updateCategoryAttribute(
    id: string,
    data: {
      label?: string
      type?: string
      unit?: string | null
      sort_order?: number
      deleted_at?: string
    }
  ) {
    const updateData: Record<string, any> = { ...data }
    if (data.label) {
      updateData.key = this.generateKey(data.label)
    }
    // @ts-ignore - method generated by MedusaService
    return await this.updateCategoryCustomAttributes([{ id, ...updateData }])
  }

  async listGlobalAttributes() {
    // @ts-ignore - generated
    return await this.listCategoryCustomAttributes({
      is_global: true,
      deleted_at: null,
    })
  }

  async createProductAttribute(data: {
    product_id: string
    category_custom_attribute_id: string
    value: string
    value_numeric?: number | null
    value_file?: string | null
  }) {
    // @ts-ignore - method generated by MedusaService
    return await this.createProductCustomAttributes(data)
  }

  async updateProductAttribute(
    id: string,
    data: {
      value?: string
      value_numeric?: number | null
      value_file?: string | null
      deleted_at?: string
    }
  ) {
    // @ts-ignore - method generated by MedusaService
    return await this.updateProductCustomAttributes([{ id, ...data }])
  }

  async getProductAttributes(productId: string) {
    // @ts-ignore - method generated by MedusaService
    return await this.listProductCustomAttributes({
      product_id: productId,
      deleted_at: null,
    }, {
      relations: ["category_custom_attribute"],
    })
  }

  async listTemplates() {
    // @ts-ignore - generated
    return await this.listAttributeTemplates({ deleted_at: null })
  }

  async createTemplate(data: {
    label: string
    type?: string
    unit?: string | null
    description?: string | null
  }) {
    const key = this.generateKey(data.label)
    // @ts-ignore - generated
    return await this.createAttributeTemplates({
      label: data.label,
      key,
      type: data.type || "text",
      unit: data.unit ?? null,
      description: data.description ?? null,
    })
  }

  async updateTemplate(
    id: string,
    data: {
      label?: string
      type?: string
      unit?: string | null
      description?: string | null
      deleted_at?: string
    }
  ) {
    const updateData: Record<string, any> = { ...data }
    if (data.label) {
      updateData.key = this.generateKey(data.label)
    }
    // @ts-ignore - generated
    return await this.updateAttributeTemplates([{ id, ...updateData }])
  }

  async applyTemplateToCategory(templateId: string, categoryId: string) {
    // @ts-ignore - generated
    const template = await this.retrieveAttributeTemplate(templateId)
    return await this.createCategoryAttribute({
      label: template.label,
      type: template.type,
      unit: template.unit,
      category_id: categoryId,
      is_standard: true,
    })
  }

  private generateKey(label: string): string {
    return slugify(label, { separator: "_", lowercase: true }) || "attr"
  }
}

export default CustomAttributeService
